name: Automerge release bump PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    name: dump GITHUB Context
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: dump
        run: echo "$GITHUB_CONTEXT"
  autoapprove:
    if: contains(github.event.label.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

  automerge:
    needs: [autoapprove]
    if: contains(github.event.label.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.7.5
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GITHUB_LOGIN: asyncapi-bot
          MERGE_METHOD: rebase
          MERGE_COMMIT_MESSAGE: 'pull-request-title'
          MERGE_RETRIES: '10'
          MERGE_RETRY_SLEEP: '10000'
