# Action to release after a pull request merges with master

name: Create Release

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release:
    name: 'Release NPM, GitHub, Docker'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
          check-latest: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Get version from package.json before release step
        id: initversion
        uses: martinbeentjes/npm-get-version-action@master
      - name: Release to NPM and GitHub
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: yarn release
      - name: Get version from package.json after release step
        id: extractver
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create Pull Request with updated package files
        id: cpr
        if: steps.initversion.outputs.current-version != steps.extractver.outputs.current-version
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(release): ${{ steps.extractver.outputs.current-version }}'
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: 'chore(release): ${{ steps.extractver.outputs.current-version }}'
          body: 'Version bump in package.json and package-lock.json for release [${{ steps.extractver.outputs.current-version }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.extractver.outputs.current-version }})'
          branch: version-bump/${{ steps.extractver.outputs.current-version }}
          labels: automerge
          delete-branch: true
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: rebase
