# Action to release after a pull request merges with master

name: Create Release

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release:
    name: 'Release NPM, GitHub, Docker'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
          check-latest: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Get version from package.json before release step
        id: initversion
        uses: martinbeentjes/npm-get-version-action@master
      - name: Release to NPM and GitHub
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: bump-bot
          GIT_AUTHOR_EMAIL: info@bump.io
          GIT_COMMITTER_NAME: bump-bot
          GIT_COMMITTER_EMAIL: info@bump.io
        run: yarn release
      - name: Get version from package.json after release step
        id: extractver
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create Pull Request with updated package files
        if: steps.initversion.outputs.current-version != steps.extractver.outputs.current-version
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(release): ${{ steps.extractver.outputs.current-version }}'
          committer: bump-bot <info@bump.io>
          author: bump-bot <info@bump.io>
          title: 'chore(release): ${{ steps.extractver.outputs.current-version }}'
          body: 'Version bump in package.json and package-lock.json for release [${{ steps.extractver.outputs.current-version }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.extractver.outputs.current-version }})'
          branch: version-bump/${{ steps.extractver.outputs.current-version }}
