# Action to release after a pull request merges with master

name: Create Release

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release-on-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          git-user-name: 'Release Action'
          git-user-email: 'changelog@github.actions.com'
          preset: 'angular'
          tag-prefix: 'v'
          release-count: '0'
          skip-on-empty: 'false'
          skip-version-file: 'false'
          skip-commit: 'false'

