# Action to release after a pull request merges with master

name: Create Release

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release-on-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn add standard-version
      - name: Create Release
        run: yarn release
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global push.followTags true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
