# This is a basic workflow to help you get started with Actions
# used to test actions

name: test-workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          git-user-name: 'Release Action'
          git-user-email: 'changelog@github.actions.com'
          preset: 'angular'
          tag-prefix: 'v'
          release-count: '0'
          skip-on-empty: 'false'
          skip-version-file: 'false'
          skip-commit: 'false'
